version: '3'

services: 
  mongo:
    image: mongo
    restart: always
    volumes: 
      - localdatabase:/data/db
    networks: 
      - composenetwork

  mongo-express:
    image: mongo-express
    restart: always
    ports: 
      - 8081:8081
    environment: 
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    networks: 
      - composenetwork
    depends_on: 
      - mongo

volumes:
  localdatabase:

networks:
  composenetwork:
    driver: bridge
